fmrest.fmrest_server.*:
  type: config_entity
  label: 'FileMaker REST Server config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    url:
      type: string
      label: 'Base URL'
    db:
      type: string
      label: 'Database'
    version:
      type: string
      label: 'API version'
    key:
      type: string
      label: 'Credentials key'
